from server.db.models import Problem, Attempt, Event, State

def upsert_problem(problem_data: dict) -> None: ...
def get_problem(problem_id: str) -> Problem | None: ...
def list_problems(difficulty: str | None = None, tag: str | None = None) -> list[Problem]: ...
def create_attempt(problem_id: str, language: str) -> Attempt: ...
def get_attempt(attempt_id: str) -> Attempt | None: ...
def get_active_attempt() -> Attempt | None: ...
def set_active_attempt(attempt_id: str) -> None: ...
def clear_active_attempt() -> None: ...
def mark_completed(attempt_id: str) -> None: ...
def record_event(attempt_id: str, kind: str, payload: dict | None = None) -> Event: ...